wip: add offer status to open api definition
mission-apprentissage/api-apprentissage pull request #258
Opened 2024-12-09 17:12 UTC by sbenfares

WIP (update des snapshot à faire)

2024-12-13 13:59 UTC, moroine requested changes

2024-12-13 13:59 UTC, moroine commented on package.json
> +    "magic-string": "0.30.15"
Pourquoi à tu besoin de fixer les resolutions ?

2024-12-17 08:14 UTC, sbenfares commented on package.json
> +    "magic-string": "0.30.15"
Effet de bord de l'upgrade de vitest je pense, cf 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/actions/runs/12293581527/job/34306561663#step:6:20

2024-12-18 14:45 UTC, moroine requested changes

2024-12-18 14:45 UTC, moroine commented on package.json
> +    "magic-string": "0.30.15"
--> Il faut lancer `yarn dedupe`

2024-12-19 09:11 UTC, sbenfares commented on package.json
> +    "magic-string": "0.30.15"
Done avec suppression des resolutions 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/258/commits/e84188c87c51da2959c7a93033a6be0bf50654ef

2024-12-19 09:17 UTC, moroine requested changes

2024-12-19 09:17 UTC, moroine commented on package.json
> -    "exceljs@^4.4.0": "patch:exceljs@npm%3A4.4.0#./.yarn/patches/exceljs-npm-4.4.0-15bcfdd142.patch"
Par contre cette résolution est importante (c'est un patch)

2024-12-19 09:29 UTC, sbenfares commented on package.json
> -    "exceljs@^4.4.0": "patch:exceljs@npm%3A4.4.0#./.yarn/patches/exceljs-npm-4.4.0-15bcfdd142.patch"
👍🏼 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/258/commits/d114bbdc634074e3cc66436d1621e21137c8b11c

2024-12-19 21:07 UTC, moroine approved these changes

2024-12-19 21:12 UTC, merged