feat(ui): traduction des composants utilisateurs
mission-apprentissage/api-apprentissage pull request #260
Opened 2024-12-12 15:06 UTC by sbenfares

Traduction des composants liés à l'inscription / connexion / page utilisateur

2024-12-18 14:56 UTC, moroine requested changes

2024-12-18 14:56 UTC, moroine commented on ui/app/[lang]/compte/profil/components/GenerateApiKey.tsx
>    }, [statut]);
Manque `t` & `lang` dans le `useMemo`

2024-12-18 14:56 UTC, moroine commented on ui/app/[lang]/compte/profil/page.tsx
> +          : t("monCompte.actif", { lng: lang });
```suggestion
      const expired = new Date(apiKey.expires_at) < new Date();
      const statut =
        expired
          ? t("monCompte.expire", { lng: lang })
          : t("monCompte.actif", { lng: lang });
```

2024-12-18 14:56 UTC, moroine commented on ui/app/[lang]/compte/profil/page.tsx
>                : fr.colors.decisions.text.label.pinkTuile.default
```suggestion
            expired
              ? fr.colors.decisions.text.label.pinkTuile.default
              : fr.colors.decisions.artwork.minor.greenBourgeon.default
```

2024-12-18 14:56 UTC, moroine commented on ui/app/[lang]/compte/profil/page.tsx
> +              statut === t("monCompte.actif", { lng: lang })
```suggestion
              !expired
```

2024-12-18 14:56 UTC, moroine commented on ui/utils/routes.utils.test.ts
> +      const normalizedPath = name.split(path.sep).join("/");
Sur Windows t'as un soucis de slash du coup ?

2024-12-18 14:56 UTC, moroine commented on ui/utils/routes.utils.test.ts
>      expect(Object.keys(PAGES.static).length + Object.keys(PAGES.dynamic).length).toBe(
A supprimer les logs

2024-12-19 13:37 UTC, sbenfares commented on ui/utils/routes.utils.test.ts
> +      const normalizedPath = name.split(path.sep).join("/");
Exactement readdirSync dans un env local Windows = 🤯

2024-12-19 13:58 UTC, sbenfares commented on ui/utils/routes.utils.test.ts
>      expect(Object.keys(PAGES.static).length + Object.keys(PAGES.dynamic).length).toBe(
Done here 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/260/commits/cb9a3ea779ea81ddc2c2d04c667f3f2d4e920a67

2024-12-19 13:58 UTC, sbenfares commented on ui/app/[lang]/compte/profil/page.tsx
> +              statut === t("monCompte.actif", { lng: lang })
Done here 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/260/commits/a1ca940af71c75a9d23d329975a8e4a0712c2644

2024-12-19 13:58 UTC, sbenfares commented on ui/app/[lang]/compte/profil/page.tsx
>                : fr.colors.decisions.text.label.pinkTuile.default
Done here 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/260/commits/a1ca940af71c75a9d23d329975a8e4a0712c2644

2024-12-19 13:58 UTC, sbenfares commented on ui/app/[lang]/compte/profil/page.tsx
> +          : t("monCompte.actif", { lng: lang });
Done here 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/260/commits/a1ca940af71c75a9d23d329975a8e4a0712c2644

2024-12-19 15:19 UTC, sbenfares commented on ui/app/[lang]/compte/profil/components/GenerateApiKey.tsx
>    }, [statut]);
Done avec qqs correctifs

2024-12-19 21:07 UTC, moroine requested changes

2024-12-19 21:07 UTC, moroine commented on ui/app/[lang]/compte/profil/page.tsx
> +        {/* <ManageApiKeysBanner key="api-key-banner" lang={lang} t={t} /> */}
😬

2024-12-19 22:13 UTC, sbenfares commented on ui/app/[lang]/compte/profil/page.tsx
> +        {/* <ManageApiKeysBanner key="api-key-banner" lang={lang} t={t} /> */}
Déso 🙏🏼 👉🏼 https://github.com/mission-apprentissage/api-apprentissage/pull/260/commits/6fc395e6652606e027e99848511f6c9063d22ca6

2024-12-20 07:43 UTC, merged